### ISSUE TITLE
proper schematics with connection dots

### ISSUE THREAD

**Issue by DangerPie** [martinloren/HScope#27]
Please make proper schematics with connection dots. Current schemes is confusing and forcing me to figure out correct wiring.

![](http://i.imgur.com/ruB86cT.png)

**Comment by martinloren** [comment]
Thanks for clear schematic! Will try to figure out how to implement in the drawing software!

**Comment by DangerPie** [comment]
Thanks. I drawed it in DIYLC.

**Comment by martinloren** [comment]
New schematics will be provided with EasyEDA. Please check it here: https://easyeda.com/martinloren
