### ISSUE TITLE
HXML

### ISSUE THREAD

**Issue by RomanB1000** [martinloren/HScope#28]
When I save Oscilloscope data, it saves as a zip file with a nice picture and hxml data. Unfortunately, I can not do anything with the xhml file. How can I convert that data to CSV?

**Comment by martinloren** [comment]
This data currently cannot be converted in CSV since the amount of points is greater than excel capabilities. In really required I may add an exported limited to a maximum amount of points, like 65.000. Please advice.

**Comment by martinloren** [comment]
In latest version CSV data can be exported with Automotive module up to 1ML points.
