### ISSUE TITLE
HScope on windows 10 problem.

### ISSUE THREAD

**Issue by mazzerman** [martinloren/HScope#29]
I have installed Hscope on Nox on a windows 10 tablet but it doesn't recognise my hantek 1008C it only opens in demo mode, but its a registered version. I have tried using direct USB into tablet and also with converter lead from USB to mini USB. It works fine on tablet with hantek software but not through Nox with HScope software. Am I missing something ?

**Comment by martinloren** [comment]
I've never tested on emulators but some user reported emulators working with HScope in particular with the USB port. You can check a couple indicated under OS at the table at this page: http://www.martinloren.com/hscope
