### ISSUE TITLE
HS102 Pro

### ISSUE THREAD

**Issue by ddexdd** [martinloren/HScope#31]
I was going to build the HS101 Pro and noticed in the HScope app and on the firmware since version 8 there is support for HS102 Pro. 

I'm unable to locate the schematics for a HS102 Pro on Github or your HS10X website.  Can you tell me if the feature of HS102 Pro is available?

Thanks,

**Comment by martinloren** [comment]
Probably the HS102 Pro will not be implemented since the new HS402 which will provide better performances.
