### ISSUE TITLE
BUG: HS102 Pro Channel 2 AC/DC selection on reconnect

### ISSUE THREAD

**Issue by gadjex** [martinloren/HScope#33]
On an HS102 Pro, after turning on channel 2 to DC mode and then disconnecting the USB and reconnecting, the app will erroneously show DC mode on channel 2 when it is actually in AC mode. Switching channel 2 off and then back to DC mode will fix the issue until the next disconnect and 
reconnect.

This is confirmed by using a volt meter and checking pin PB13 is at 0 volts after reconnecting.

Channel 1 does not display this improper behavior.

**Comment by martinloren** [comment]
Thanks for reporting this issue. What is the firmware version?

**Comment by gadjex** [comment]
Happens with v9 and v10.1

**Comment by martinloren** [comment]
Confirmed, it is a bug on HScope, it will be fixed in next Beta release. By the way there is no documentation for the HS102 Pro but the firmware is working probably....did you build it? I mean with the PGA and all range of input voltages or just single voltage range?

**Comment by gadjex** [comment]
I built it with 2 PGAs 2 SSRs and 2 AMS1117. Both channels work +-15V. I
haven't fully tested it. I can send you the schematic when I get home
tomorrow. It really is just a HS101 Pro with a duplicate channel.

**Comment by martinloren** [comment]
This issue should have been solved in the latest HScope release.
