### ISSUE TITLE
Hscope on Chrome OS / Chromebook?

### ISSUE THREAD

**Issue by derek-eder** [martinloren/HScope#35]
The title (hopefully) says it all!  Has anyone tried to run Hscope under Chrome?

**Comment by Hummtaro** [comment]
Does not work, Android on ChromeOS does not have usb support..

**Comment by martinloren** [comment]
Confirmed, Chromebook still do not support USB OTG devices. It is a feature waiting for an OS update.  Check here:

https://developer.android.com/topic/arc/manifest

It's just funny that Chromebook is a Google product right? :D
