### ISSUE TITLE
Problems with hantek 1008C not recognised.

### ISSUE THREAD

**Issue by mazzerman** [martinloren/HScope#36]
Hi. I have the paid full vesion with automotive module. I bought an Android pad with OTG compatibility. (Tested with OTG check app). I also bought OTG compatible USB C connector. I launch Hscope but it will only show DEMO mode. It says device not connected. I have the Hantek powered separately. Are there any drivers I need to install alongside the Hscope app?
Regards

**Comment by mazzerman** [comment]
I have an android pad that is confirmed OTG compatible. I have also now purchased 3 different OTG connectors 2 small cable style with mini C USB to standard USB  and the software still stays in demo mode can someone please help because I've had this software for a few months and never been able to use it.
![IMG_20200812_142931](https://user-images.githubusercontent.com/64361140/90015092-61b3a100-dca8-11ea-8556-98d29ac43a55.jpg)

**Comment by mazzerman** [comment]
![20200812_145307](https://user-images.githubusercontent.com/64361140/90019313-84e14f00-dcae-11ea-9fc6-e5b4c2c5b61f.jpg)
![20200812_145222](https://user-images.githubusercontent.com/64361140/90019317-86ab1280-dcae-11ea-9590-1b34312ac41e.jpg)
![20200812_145242](https://user-images.githubusercontent.com/64361140/90019319-8743a900-dcae-11ea-8617-e469e8aa5f99.jpg)
![20200812_145252](https://user-images.githubusercontent.com/64361140/90019322-87dc3f80-dcae-11ea-8cad-ca222ac0a311.jpg)
![20200812_145232](https://user-images.githubusercontent.com/64361140/90019325-8874d600-dcae-11ea-8518-b0bffe177215.jpg)
![20200812_145342](https://user-images.githubusercontent.com/64361140/90019330-89a60300-dcae-11ea-9251-a7c57d3abde8.jpg)

**Comment by martinloren** [comment]
It may depend from the tablet, try any other phone, can also ask a friend to try with his phone. Check also the testing methods here: https://www.martinloren.com/hscope/how-can-we-help-you/

**Comment by mazzerman** [comment]
Hi I cannot get Hscope to work with my Lenovo android pad.
The only USB options are on the attached photo. That is with it plugged into the laptop.
With the OTG cohort cable it greys out.[Image]
________________________________
