### ISSUE TITLE
LASTEST VERSION OF HSCOPE CRASHES DURING PROBE SETUP

### ISSUE THREAD

**Issue by crawlbug** [martinloren/HScope#41]
Using an ONN 100011886 tablet, the new version of HSCOPE, updated from the Play Store on Sept 4, 2021, crashes when attempting to change probe settings in setup. After crash, rerunning the app shows that the change requested in the probe setup was made, just crashes the app and requires rerun. Problem noted in demo, and online 6022BE modes.

**Comment by martinloren** [comment]
What Android version? Try the latest Beta...

**Comment by martinloren** [comment]
Checking

**Comment by martinloren** [comment]
This problem should be fixed in the latest release.
