### ISSUE TITLE
Question on Data Logging capability in HScope

### ISSUE THREAD

**Issue by set-tech** [martinloren/HScope#42]
Hi All, 

I have a Hantek 6022BL USB scope/logic analyser. I would like to use this device to perform long term (like 24 hours) voltage monitoring with a low sample rate (like 1 Hz (Sa/s) or less). 

Unfortunately, neither OpenHantek nor PulseView seems to offer this functionality for the 6022BL. I would like to explore whether the Data Logging feature within HScope could be used to perform this function please?

Thanks for any support.

Shane,

**Comment by martinloren** [comment]
Yes with HScope Data Logger you can get 24H or more hours of statistics according the selected sampling interval (from 1/4 of second up). Beside the single data point you get recorded also other statistics like MAX and MIN in that interval. Export is available in CSV format.
